# Site settings
title: Winnie Fong
description: 'BASc in Biomedical Engineering with a focus in Computer Engineering. 2019 grad from the University of Waterloo'
url: 'http://winnf.github.io'
baseurl: '/winnf'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Winnie Fong'
  email: winnie.fongg@gmail.com
  #twitter_username: joshgerdes
  #facebook_username: joshgerdes
  github_username:  winnf
  linkedin_username:  winnf

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
